### ISSUE TITLE
Clock run backward

### ISSUE THREAD

**Issue by nxenara** [sanghviharshit/wandering-hour-clock#1]
Hello,

The clock is running counterclockwise.
With this change the clock turns clockwise but commands, +5minutes, -5minutes, demo and recycle are still reversed.

<code> myStepper.step(-cStep); //inversion du mouvement, cStep modifié en -cStep </code>

This is certainly not the right solution.

Thank you for your help.

Nxenara

**Comment by sanghviharshit** [comment]
I think there might be an issue with the wiring order. Have you tested it with a basic sketch from [ESP32](https://randomnerdtutorials.com/esp32-stepper-motor-28byj-48-uln2003/) or [ESP8266](https://randomnerdtutorials.com/esp8266-nodemcu-stepper-motor-28byj-48-uln2003/)?
