### ISSUE TITLE
Your wiring diagram is not exactly what you have in ur pictures. 

### ISSUE THREAD

**Issue by Bock326** [sanghviharshit/wandering-hour-clock#2]
The schematic shows that both boards are connected to ground and only the stepper driver is power by 5v. In your image of your irl wiring 5v is also connected to the esp32

**Comment by sanghviharshit** [comment]
The wiring diagram is from the tutorial I have linked, and it assumes you are powering your ESP32 board using the micro-usb port. I have decided to power the stepper motor and the board from the same power supply. Hope that helps!
